=== IntersectAustralia/CloudStor/collections/apps/collections/schema/schema_spec.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://schema.intersect.org.au/Collections/metadata/1.1/schema_spec.json",
    "title": "Collections Metadata Schema Specification v1.1",
    "description": "This schema defines the syntax of a valid metadata model for use within the Collections application",
    "type": "object",
    "required": [
        "id",
        "display_name",
        "version",
        "scope",
        "description",
        "packaged_metadata_template",
        "exported_metadata_template",
        "readme_template",
        "metadata_categories"
    ],
    "properties": {
        "id": {
            "title": "Schema id",
            "description": "The unique identifier of the schema",
            "type": "string",
            "pattern": "^[a-zA-Z0-9]+(?:(?:-|\\.)[a-zA-Z0-9]+)*$"
        },
        "display_name": {
            "title": "Schema display name",
            "description": "The name of the schema to be displayed within the application",
            "type": "string"
        },
        "version": {
            "title": "Schema version",
            "description": "Current version of this schema",
            "type": "string",
            "pattern": "^[0-9]+(?:\\.[0-9]+){0,2}$"
        },
        "scope" : {
          "title": "Scope",
          "description": "The University, Faculty, or Organisation that the schema relates to",
          "type":"string"
        },
        "description": {
            "title": "Schema description",
            "description": "Description of the schema",
            "type": "string"
        },
        "packaged_metadata_template": {
            "title": "Packaged metadata template",
            "description": "Mustache template to use for the metadata XML file within a packaged collection",
            "type": "object",
            "required": [
                "template_directory",
                "template_name",
                "partials_directory"
            ],
            "properties": {
                "template_directory": {
                    "title": "Packaged metadata template directory path",
                    "description": "Path to the parent directory of the packaged metadata template file",
                    "type": "string"
                },
                "template_name": {
                    "title": "Packaged metadata template file basename",
                    "description": "Basename of the packaged metadata template file",
                    "type": "string"
                },
                "partials_directory": {
                    "title": "Packaged metadata template partials directory path",
                    "description": "Path to the partials directory for the packaged metadata template file or null if no partials used",
                    "type": ["string", "null"]
                }
            },
            "additionalProperties": false
        },
        "exported_metadata_template": {
            "title": "Exported metadata template",
            "description": "Mustache template to use for the exported collection metadata XML file",
            "type": "object",
            "required": [
                "template_directory",
                "template_name",
                "partials_directory"
            ],
            "properties": {
                "template_directory": {
                    "title": "Exported metadata template directory path",
                    "description": "Path to the parent directory of the exported metadata template file",
                    "type": "string"
                },
                "template_name": {
                    "title": "Exported metadata template file basename",
                    "description": "Basename of the exported metadata template file",
                    "type": "string"
                },
                "partials_directory": {
                    "title": "Exported metadata template partials directory path",
                    "description": "Path to the partials directory for the exported metadata template file or null if no partials used",
                    "type": ["string", "null"]
                }
            },
            "additionalProperties": false
        },
        "readme_template": {
            "title": "README template",
            "description": "Mustache template to use for the Collection README file",
            "type": "object",
            "required": [
                "template_directory",
                "template_name",
                "partials_directory"
            ],
            "properties": {
                "template_directory": {
                    "title": "README template directory path",
                    "description": "Path to the parent directory of the README template file",
                    "type": "string"
                },
                "template_name": {
                    "title": "README template file basename",
                    "description": "Basename of the README template file",
                    "type": "string"
                },
                "partials_directory": {
                    "title": "README template partials directory path",
                    "description": "Path to the partials directory for the README template file or null if no partials used",
                    "type": ["string", "null"]
                }
            },
            "additionalProperties": false
        },
        "metadata_categories": {
            "title": "Collection metadata categories",
            "description": "A set of metadata categories to display within the application metadata UI",
            "type": "array",
            "items": { "$ref": "#/definitions/metadata_category" }
        }
    },
    "additionalProperties": true,

    "definitions": {
        "metadata_category": {
            "title": "Collection metadata category",
            "description": "A category of metadata which describes the collection",
            "type": "object",
            "required": [
                "id",
                "display_name",
                "description",
                "category_nodes"
            ],
            "properties": {
                "id": {
                    "title": "Category id",
                    "description": "The unique identifier for the category",
                    "type": "string",
                    "pattern": "^[a-zA-Z][a-zA-Z0-9_]*$"
                },
                "display_name": {
                    "title": "Category display name",
                    "description": "The category name to be displayed within the application",
                    "type": "string"
                },
                "description": {
                    "title": "Category description",
                    "description": "Description of the metadata category",
                    "type": ["string", "null"]
                },
                "category_nodes": {
                    "title": "Category metadata nodes",
                    "description": "A set of metadata to be displayed within this metadata category",
                    "type": "array",
                    "items": { "$ref": "#/definitions/category_node" }
                }
            },
            "additionalProperties": false
        },

        "category_node": {
            "title": "Metadata category node",
            "description": "A metadata node contained within a category, either a metadata group or field",
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "title": "Metadata category node type",
                    "description": "The type of metadata node to display within the metadata category",
                    "type": "string",
                    "enum": ["metadata_group", "metadata_field"]
                }
            },
            "patternProperties": {
                "^metadata_(group|field)$": {
                    "title": "Metadata category node type specification",
                    "description": "Specification of the metadata category node",
                    "oneOf": [
                        { "$ref": "#/definitions/metadata_group" },
                        { "$ref": "#/definitions/metadata_field" }
                    ]
                }
            },
            "minProperties": 2,
            "maxProperties": 2,
            "additionalProperties": false
        },

        "metadata_node": {
          "title": "Metadata node",
            "description": "A set of generic metadata node properties",
            "type": "object",
            "required": [
                "id",
                "display_name",
                "description",
                "tooltip",
                "min_occurs",
                "max_occurs"
            ],
            "properties": {
                "id": {
                    "title": "Node id",
                    "description": "The unique identifier for the node",
                    "type": "string",
                    "pattern": "^[a-zA-Z][a-zA-Z0-9_]*$"
                },
                "display_name": {
                    "title": "Display name",
                    "description": "The node name to be displayed within the application",
                    "type": "string"
                },
                "description": {
                    "title": "Description",
                    "description": "Description of the metadata node",
                    "type": ["string", "null"]
                },
                "tooltip": {
                    "title": "Tooltip",
                    "description": "The tooltip to display when hovering over the name of the node within the application",
                    "type": ["string", "null"]
                },
                "min_occurs": {
                    "title": "Minimum occurrences",
                    "description": "Minimum number of node occurrences to display within the application",
                    "type": "integer",
                    "minimum": 0,
                    "exclusiveMinimum": false
                },
                "max_occurs": {
                    "title": "Maximum occurrences",
                    "description": "Maximum number of node occurrences to display within the application",
                    "type": "integer",
                    "minimum": 0,
                    "exclusiveMinimum": true
                }
            }
        },

        "metadata_group": {
            "title": "Metadata group",
            "description": "A group of metadata fields",
            "allOf": [
                { "$ref": "#/definitions/metadata_node" },
                {
                    "required": [
                        "metadata_fields"
                    ],
                    "properties": {
                        "metadata_fields": {
                            "title": "Group metadata fields",
                            "description": "A set of metadata fields to be displayed within this metadata group",
                            "type": "array",
                            "items": { "$ref": "#/definitions/metadata_field" }
                        },
                        "occurrence_display_name": {
                            "title": "Group occurrence display name",
                            "description": "Display name to use for an occurrence of the group",
                            "type": ["string", "null"]
                        }
                    }
                }
            ],
            "properties": {
                "id": {},
                "display_name": {},
                "occurrence_display_name": {},
                "description": {},
                "tooltip": {},
                "min_occurs": {},
                "max_occurs": {},
                "metadata_fields": {}
            },
            "additionalProperties": false
        },

        "metadata_field": {
            "title": "Metadata field",
            "description": "A field of metadata which describes the collection",
            "allOf": [
                { "$ref": "#/definitions/metadata_node" },
                {
                    "required": [
                        "mandatory",
                        "field"
                    ],
                    "properties": {
                        "mandatory": {
                            "title": "Required field indicator",
                            "description": "Indicates whether this metadata field is required in order for the collection metadata to be considered valid",
                            "type": "boolean"
                        },
                        "field": { "$ref": "#/definitions/field" }
                    }
                }
            ],
            "properties": {
                "id": {},
                "display_name": {},
                "description": {},
                "tooltip": {},
                "min_occurs": {},
                "max_occurs": {},
                "mandatory": {},
                "field": {}
            },
            "additionalProperties": false
        },

        "field": {
            "title": "Metadata field display type",
            "description": "Description of the type of metadata field to display",
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "title": "Metadata field display type",
                    "description": "The type of metadata field to display",
                    "type": "string",
                    "enum": ["text_field", "number_field", "date_field", "single_select_field"]
                }
            },
            "patternProperties": {
                "^(text|number|date|single_select)_field$": {
                    "title": "Metadata field display type specification",
                    "description": "Specification of the previously selected metadata field display type",
                    "oneOf": [
                        { "$ref": "#/definitions/text_field" },
                        { "$ref": "#/definitions/number_field" },
                        { "$ref": "#/definitions/date_field" },
                        { "$ref": "#/definitions/single_select_field" }
                    ]
                }
            },
            "minProperties": 2,
            "maxProperties": 2,
            "additionalProperties": false
        },

        "text_field": {
            "title": "Text based metadata field",
            "description": "Specification of text field properties",
            "type": "object",
            "required": [
                "char_limit",
                "placeholder",
                "value"
            ],
            "properties": {
                "char_limit": {
                    "title": "Text field character limit",
                    "description": "Upper limit of how many characters can be entered into the text field",
                    "type": ["integer", "null"],
                    "minimum": 0,
                    "exclusiveMinimum": true
                },
                "placeholder": {
                    "title": "Text field placeholder",
                    "description": "Placeholder value to initially display within the text field",
                    "type": "string"
                },
                "value": {
                    "title": "Text field default value",
                    "description": "Default textual value to populate the text field with upon creation",
                    "type": ["string", "null"]
                },
                "num_rows": {
                    "title": "Text Area Rows",
                    "description": "Number of rows to display in the text field",
                    "type": "integer",
                    "pattern": "^[1-9]{1}[0-9]*$"
                }
            },
            "additionalProperties": false
        },

        "number_field": {
            "title": "Number based metadata field",
            "description": "Specification of number field properties",
            "type": "object",
            "required": [
                "placeholder",
                "value"
            ],
            "properties": {
                "placeholder": {
                    "title": "Number field placeholder",
                    "description": "Placeholder value to initially display within the number field",
                    "type": "string"
                },
                "value": {
                    "title": "Number field default value",
                    "description": "Default number value to populate the field with upon creation",
                    "type": ["number", "null"]
                }
            },
            "additionalProperties": false
        },

        "date_field": {
            "title": "Date based metadata field",
            "description": "Specification of date field properties",
            "type": "object",
            "required": [
                "min_date",
                "max_date",
                "value"
            ],
            "properties": {
                "min_date": {
                    "title": "Minimum selectable date",
                    "description": "Minimum date that can be selected within the application datepicker in the format 'yyyy-mm-dd'",
                    "type": ["string", "null"],
                    "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
                },
                "max_date": {
                    "title": "Maximum selectable date",
                    "description": "Maximum date that can be selected within the application datepicker in the format 'yyyy-mm-dd'",
                    "type": ["string", "null"],
                    "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
                },
                "value": {
                    "title": "Date field default value",
                    "description": "Default date to use upon field creation which can either be 'today' or a date in the format 'yyyy-mm-dd'",
                    "type": ["string", "null"],
                    "pattern": "^today|([0-9]{4}-[0-9]{2}-[0-9]{2})$"
                }
            },
            "additionalProperties": false
        },

        "single_select_field": {
            "title": "Single select metadata field",
            "description": "Specification of single select metadata field properties",
            "type": "object",
            "required": [
                "options"
            ],
            "properties": {
                "value": {
                    "title": "Default selected value",
                    "description": "Default value to have selected in the field upon creation, should match an option",
                    "type": ["string", "null"]
                },
                "options": {
                    "title": "Option set",
                    "description": "Set of values to be available for selection",
                    "type": "array",
                    "uniqueItems": true,
                    "items": {
                        "type": "string",
                        "minItems": 1
                    }
                }
            }
        }
    }
}

=== IntersectAustralia/CloudStor/collections/apps/collections/schema/metadata-schemas/archaeology.json
{
    "id":"archaeology",
    "display_name":"Achaeology Find",
    "version": "1",
    "scope": "Public",
    "description":"Metadata related to artefacts found on archaeological digs.",
    "readme_template": {
        "template_directory": "Public/templates/archaeology",
        "template_name": "archaeology_readme.html.mustache",
        "partials_directory": "Public/templates/partials"
    },
    "packaged_metadata_template": {
        "template_directory": "Public/templates/archaeology",
        "template_name": "archaeology_metadata.xml.mustache",
        "partials_directory": null
    },
    "exported_metadata_template": {
        "template_directory": "Public/templates/archaeology",
        "template_name": "archaeology_metadata.xml.mustache",
        "partials_directory": null
    },
    "metadata_categories":[
        {
            "id":"summary",
            "display_name":"Dig Summary",
            "description":null,
            "category_nodes":[
                {
                    "type":"metadata_field",
                    "metadata_field":{
                        "id":"dignumber",
                        "display_name":"Dig ID number",
                        "description":"Id number of the dig.",
                        "tooltip":"Dig ID number",
                        "mandatory":true,
                        "min_occurs":1,
                        "max_occurs":1,
                        "field":{
                            "type":"text_field",
                            "text_field":{
                                "char_limit":null,
                                "placeholder":"",
                                "value":null
                            }
                        }
                    }
                },
                {
                    "type":"metadata_field",
                    "metadata_field":{
                        "id":"description",
                        "display_name":"Description",
                        "description":"Description of the dig.",
                        "tooltip": "",
                        "mandatory":false,
                        "min_occurs":1,
                        "max_occurs":1,
                        "field":{
                            "type":"text_field",
                            "text_field":{
                                "char_limit":null,
                                "placeholder":"",
                                "value":null
                            }
                        }
                    }
                },
                {
                    "type":"metadata_field",
                    "metadata_field":{
                        "id":"location",
                        "display_name":"Dig Location",
                        "description":"Location of the dig site.",
                        "tooltip": "",
                        "mandatory":false,
                        "min_occurs":1,
                        "max_occurs":1,
                        "field":{
                            "type":"text_field",
                            "text_field":{
                                "char_limit":null,
                                "placeholder":"",
                                "value":null
                            }
                        }
                    }
                }
            ]
        },
        {
            "id":"finds",
            "display_name":"Finds",
            "description":null,
            "category_nodes":[
                { 
                    "type":"metadata_group",
                    "metadata_group":{
                        "id":"artefacts",
                        "display_name":"Artefact",
                        "description":"Found Artefact",
                        "tooltip":"An artefact found on the dig site",
                        "min_occurs":1,
                        "max_occurs":1000000,
                        "metadata_fields":[
                            {
                                "id":"artefactid",
                                "display_name":"ID",
                                "description":"Artefact ID",
                                "tooltip":"ID of the Artefact",
                                "mandatory":true,
                                "min_occurs":1,
                                "max_occurs":1,
                                "field":{
                                    "type":"text_field",
                                    "text_field":{
                                        "char_limit":null,
                                        "placeholder":"",
                                        "value":null
                                    }
                                }
                            },
                            {
                                "id":"description",
                                "display_name":"Description",
                                "description":"Description of the artefact",
                                "tooltip":"",
                                "mandatory":false,
                                "min_occurs":1,
                                "max_occurs":1,
                                "field":{
                                    "type":"text_field",
                                    "text_field":{
                                        "char_limit":null,
                                        "placeholder":"",
                                        "value":null
                                    }
                                }
                            },
                            {
                                "id":"datefound",
                                "display_name":"Date Found",
                                "mandatory":true,
                                "description":"Current date",
                                "tooltip":"Current date",
                                "min_occurs":1,
                                "max_occurs":1,
                                "field":{
                                    "type":"date_field",
                                    "date_field":{
                                        "min_date":"1900-01-01",
                                        "max_date":"3000-12-31",
                                        "value":"today"
                                    }
                                }
                            },
                            {
                                "id":"keyword",
                                "display_name":"Keywords",
                                "description":"Keywords to classify the artefact.",
                                "tooltip":"Classifying keywords",
                                "mandatory":false,
                                "min_occurs":0,
                                "max_occurs":10000,
                                "field":{
                                    "type":"text_field",
                                    "text_field":{
                                        "char_limit":null,
                                        "placeholder":"",
                                        "value":null
                                    }
                                }
                            }
                        ]
                    }
                }
            ]
        }
    ]
}
